### ISSUE TITLE
Should we use IRI, URI, or URL ?

### ISSUE THREAD

**Issue by iherman** [w3c/publ-wg#21]
There is certain level of confusion in the terminology. IRI (ie, rfc3987[1]) is the most general form that encompasses all internationalization requests in IETF land. It is also the reference used in the newest RDF or the Annotation recommendations.

On the other hand, at least for _locators_, the Web community has always ignored, in practice, the term IRI or URI, and they use URL. See for example, the note to the URL-s in the HTML5 standard[2] that does refer to[1] noting

> For the purpose of producing strict URLs one may wish to consider [RFC3986] [RFC3987].

There is also an active work at WhatWG defining _URL_ processing[3] which aims to be interoperable with IRI-s, ie, with RFC3987.

My proposal would be to use URL-s in our terminology, to be also in line with the Web Developer world, but making it clear in the general recommendations that we mean here RFC3987 compatible entities, the same way as HTML5 & Co. do. 

1. https://tools.ietf.org/html/rfc3987
2. https://www.w3.org/TR/html5/references.html#refsURL
3. https://url.spec.whatwg.org

**Comment by rdeltour** [comment]
> My proposal would be to use URL-s in our terminology, to be also in line with the Web Developer world, but making it clear in the general recommendations that we mean here RFC3987 compatible entities

I agree; but then, is there any reason why we shouldn't just refer to WhatWG's URL spec? (real question)

**Comment by iherman** [comment]
@rdeltour 

> I agree; but then, is there any reason why we shouldn't just refer to WhatWG's URL spec? (real question)

The WhatWG URL spec is not final, and W3C specifications' normative references should be stable documents (with a preference to standards). I think using a similar text in the specification in the terminology section as in the [html5 spec](https://www.w3.org/TR/html5/references.html#refsURL) is a safe way to go.

**Comment by rdeltour** [comment]
> The WhatWG URL spec is not final

Well, as a living standard, I don't think it will ever be "final" :-)

>  and W3C specifications' normative references should be stable documents (with a preference to standards). I think using a similar text in the specification in the terminology section as in the html5 spec is a safe way to go.

W3C's HTML does reference the WhatWG spec now, see the [URL normative reference](https://www.w3.org/TR/html/references.html#biblio-url) in the latest Rec.

**Comment by iherman** [comment]
> W3C's HTML does reference the WhatWG spec now, see the URL normative reference in the latest Rec.

Indeed, but with an explanation note of 3 paragraphs... Hence my proposal to refer to the HTML spec, and let the relevant WG describe the details...

**Comment by iherman** [comment]
Closing, per [telco resolution](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2017/2017-08-14-minutes#resolution3). Effects to be incorporated into documents.
