### ISSUE TITLE
scope of "Requirements and design options for synchronized multimedia" is unclear

### ISSUE THREAD

**Issue by whmccoy** [w3c/publ-wg#24]
The "Requirements and design options for synchronized multimedia"  doc discusses synchronizing multimedia with "content" but then mentions "book" in the next phrase. Later on it describes a requirement as pertaining to "WP/PWP". 

I believe that the ideal scope of synchronized multimedia with overall content (aka text) rendering is all OWP content not just publications. I.e. if we are going to redo and generalize EPUB 3 Media Overlays it should be applicable to web pages not just web publications. So to me the scope of this doc should be clarified as being that general. Of course we could always back off and do something for WP/PWP only but that would seem at odds with the goal of expanding the overall OWP for Publishing. But at a minimum it seems this document should clearly state its scope as that is unclear at the moment.

**Comment by iherman** [comment]
@whmccoy, this issue may have a better place on the wpub repo's issues, although it is indeed a borderline...

@TzviyaSiegman @GarthConboy ?

**Comment by GarthConboy** [comment]
I come back to the comment I made in IRC... from our charter "This
specification should generally be a functional superset of EPUB 3.1.
Functional round-tripping to/from EPUB 3.1 considered highly desirable."
(albeit on the EPUB 4 deliverable)... but, as EPUB 3.1 has MO, could be in
our purview.  Question of where (if anywhere) it will get traction.

**Comment by danielweck** [comment]
And just for reference: https://github.com/w3c/publ-wg/wiki/Requirements-and-design-options-for-synchronized-multimedia

**Comment by danielweck** [comment]
Note that this conversation will probably be migrated there:
https://github.com/w3c/sync-media-pub

(as mentioned here: http://lists.w3.org/Archives/Public/public-sync-media-pub/2018Mar/0000.html )

Also see:
https://www.w3.org/community/sync-media-pub/

**Comment by iherman** [comment]
@danielweck: once the migration is done, would you close this issue? Thanks.

**Comment by danielweck** [comment]
Sure.

**Comment by danielweck** [comment]
Let's close this, see: https://github.com/w3c/sync-media-pub/issues/1

**Comment by danielweck** [comment]
@iherman I do not have the rights to close this issue, please do :)
