### ISSUE TITLE
2019-05-06-action5: obtain manifest integrating with CORS explanation - there is an open issue for resolution as well (Dave Cramer)

### ISSUE THREAD

**Issue by iherman** [w3c/publ-wg#33]
obtain manifest integrating with CORS explanation - there is an open issue for resolution as well (Dave Cramer) ([see details](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-05-06-pwg#action5))

Cc: @dauwhe

**Comment by dauwhe** [comment]
So... just to start collecting information in this issue. [dbaron wrote](https://github.com/w3ctag/design-reviews/issues/344#issuecomment-485034489):

> Reading 3.5.1 Obtaining a Manifest made me wonder about how this is intended to integrate with CORS. I'd note that it doesn't quite seem to integrate with fetch properly, since "request" ought to link to request, and that, in turn:

> * seems to require a client (there's no "unless otherwise stated")... although that seems odd to me; it's not quite clear to me how fetch integration is supposed to work.
 
> * recommends against using the "no-cors" mode

> * It also ought to refer to the "credentials mode" rather than the "credentials".

> It's not clear to me whether the information from the manifest is going to be exposed to web content in ways that require CORS checks -- though it seems like it's probably a good idea to assume that it will at some point in the future, and thus that it's probably a good idea to use the "cors" mode. (I think that doesn't require special headers if the manifest is same-origin... although I'm not sure.)

Later he [wrote](https://github.com/w3ctag/design-reviews/issues/344#issuecomment-494433511)

> So one followup point here is that I'd like somebody with more expertise on CORS and how to integrate CORS and fetch into a specification to do a brief review of the issue I raised in the last 4-ish paragraphs of #344 (comment) .

I can safely say that I do not have more expertise on CORS than dbaron.

**Comment by dauwhe** [comment]
I will note that the web app manifest spec has a section on CSP, which mostly says

> A user agent MUST support [CSP3]. 

In turn, CSP has directives that are explicitly about [manifests](https://www.w3.org/TR/CSP3/#directive-manifest-src):

> The `manifest-src` directive restricts the URLs from which application manifests may be loaded [APPMANIFEST]. The syntax for the directive’s name and value is described by the following ABNF:

```
directive-name  = "manifest-src"
directive-value = serialized-source-list
```

Once again, our choice to avoid WAM brings us a world of complication. I'm pretty sure we will never get CSP to add a new type of manifest. Can we just say that our manifest must follow the same policy as a web app manifest?

**Comment by iherman** [comment]
> I'm pretty sure we will never get CSP to add a new type of manifest. Can we just say that our manifest must follow the same policy as a web app manifest?

First of all, at this moment, the [CSP 3 document](https://www.w3.org/TR/CSP3/) is a draft. This means that this WG group can (and probably _MUST_) contact the  [Web Application Security Working Group](https://www.w3.org/2011/webappsec/) (probably via the mailing list referred to in the header) asking them whether a publication manifest can be included in their list. That being said, it is probably a good approach to say that our manifest must follow the same policy as the WAM, but the issue (if that is an issue) whether it is all right with the CSP if the Publication Manifest relies on a different `rel` value. (The directives themselves does not seem to depend on the `rel` value, so it may simply be a matter of wording.)

**Comment by iherman** [comment]
B.t.w., for those who do not know this security world (which includes myself) this may be of interest to understand the problem: https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

**Comment by iherman** [comment]
There is an example in https://w3c.github.io/payment-method-manifest/#fetch-pmm for fetch related to another manifest. I wonder whether it is necessary to reproduce the similar level of details.

It bothers me to repeat these things in various specs like this. We may want to raise an issue with the TAG (as a response to their review) that it may be better to have some sort of a spec somewhere that can be referred to rather than re-doing the work again and again...

**Comment by iherman** [comment]
With the move to audiobooks this issue is becoming moot. Closing.
