### ISSUE TITLE
2019-05-06-action9: find a home for the Synchronized Narration spec (Wendy Reid)

### ISSUE THREAD

**Issue by iherman** [w3c/publ-wg#34]
find a home for the Synchronized Narration spec (Wendy Reid) ([see details](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-05-06-pwg#action9))

Cc: @wareid

**Comment by murata2makoto** [comment]
@wareid I would be grateful if you can make clear how this issue has been addressed.

**Comment by HadrienGardeur** [comment]
In the context of EPUB 3.3, I'd also like to know if this will have any impact on Media Overlay support as well.

IMO the relationship between Synchronized Narration Spec + SMIL/Media Overlay needs to be clarified.

**Comment by mattgarrish** [comment]
The [synchronized media community group](https://www.w3.org/community/sync-media-pub/) has taken up this work.

See: https://w3c.github.io/sync-media-pub/synchronized-narration.html
