### ISSUE TITLE
2019-05-06-action6: better explain the packaging options we rejected and why (Wendy Reid)

### ISSUE THREAD

**Issue by iherman** [w3c/publ-wg#39]
better explain the packaging options we rejected and why (Wendy Reid) ([see details](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-05-06-pwg#action6))

Cc: @wareid

**Comment by wareid** [comment]
Added additional information and clarity to the explainer last week. Waiting on a reply from Tess about questions of RSS/Atom.
