### ISSUE TITLE
2019-05-06-action4: report back to dbaron that link rel value issue is resolved (Matt Garrish)

### ISSUE THREAD

**Issue by iherman** [w3c/publ-wg#40]
report back to dbaron that link rel value issue is resolved (Matt Garrish) ([see details](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-05-06-pwg#action4))

Cc: @mattgarrish

**Comment by mattgarrish** [comment]
I've replied to the tag review issue concerning this here: https://github.com/w3ctag/design-reviews/issues/344#issuecomment-489724408
