### ISSUE TITLE
2019-05-06-action10: complete the drafts of explainers and specs (Marisa DeMeglio)

### ISSUE THREAD

**Issue by iherman** [w3c/publ-wg#43]
complete the drafts of explainers and specs (Marisa DeMeglio) ([see details](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-05-06-pwg#action10))

Cc: @marisademeglio

**Comment by TzviyaSiegman** [comment]
@marisademeglio will report to PWG on 10 June

**Comment by iherman** [comment]
With audiobooks this issue has become moot.
