### ISSUE TITLE
2019-05-06-action8: ask PinG if someone can walk us through the questionnaire because we are without an expert (Ralph Swick)

### ISSUE THREAD

**Issue by iherman** [w3c/publ-wg#44]
ask PinG if someone can walk us through the questionnaire because we are without an expert (Ralph Swick) ([see details](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-05-06-pwg#action8))

Cc: @swickr

**Comment by iherman** [comment]
Pinged @swickr ...

**Comment by samuelweiler** [comment]
Who is "us" in the case?  The WG should identify one or more stuckees who will handle this self-review.

**Comment by TzviyaSiegman** [comment]
@samuelweiler We have people in the Publishing WG who can work through the privacy aspects, but the group doesn't really have any security experts. Can we borrow a member of PING to help with self review?

**Comment by iherman** [comment]
Issue has become moot:

https://lists.w3.org/Archives/Group/group-publ-wg-chairs/2019Oct/0020.html
