### ISSUE TITLE
2019-05-07-action1: produce a gap analysis of the ucr items vs. existing web concepts (Franco Alvarado)

### ISSUE THREAD

**Issue by iherman** [w3c/publ-wg#46]
produce a gap analysis of the ucr items vs. existing web concepts (Franco Alvarado) ([see details](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-05-07-pwg#action1))

Cc: @francofaa

**Comment by TzviyaSiegman** [comment]
@francofaa please provide an update

**Comment by francofaa** [comment]
@atyposh is going through the requirements currently after I performed an initial overview of potential redundant candidates.

**Comment by iherman** [comment]
With audiobooks this issue has become moot.
