### ISSUE TITLE
2019-09-09-action1: add an informational text on using dcterms (Matt Garrish)

### ISSUE THREAD

**Issue by iherman** [w3c/publ-wg#53]
add an informational text on using dcterms (Matt Garrish) ([see details](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-09-09-pwg#action1))

Cc: @mattgarrish

**Comment by mattgarrish** [comment]
Done in https://github.com/w3c/pub-manifest/pull/59
